---
abstract: "Perl implementation of the Red/Black tree, a type of balanced binary search tree. \r"
author:
  - "Arun Prasad  C<< <arunbear@cpan.org> >>\r"
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.82'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tree-RB
no_index:
  directory:
    - inc
    - t
requires:
  enum: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/arunbear/perl5-red-black-tree
version: 0.500003
